from django.test import TestCase, Client
from django.urls import reverse
from django.contrib.auth import get_user_model
from .models import Course, Category, Enrollment

User = get_user_model()

class CourseModelTest(TestCase):
    def setUp(self):
        self.teacher = User.objects.create_user(username='teacher', email='t@t.com', password='pass', role='teacher')
        self.student = User.objects.create_user(username='student', email='s@s.com', password='pass', role='student')
        self.category = Category.objects.create(name='Python', slug='python')
        self.course = Course.objects.create(
            title='Test Course', description='A test course',
            teacher=self.teacher, status='published', level='beginner', is_free=True
        )

    def test_course_slug_autogenerated(self):
        self.assertIsNotNone(self.course.slug)
        self.assertIn('test', self.course.slug)

    def test_course_str(self):
        self.assertEqual(str(self.course), 'Test Course')

    def test_custom_manager_published(self):
        draft = Course.objects.create(title='Draft', description='...', teacher=self.teacher, status='draft', level='beginner', is_free=True)
        self.assertIn(self.course, Course.objects.published())
        self.assertNotIn(draft, Course.objects.published())

    def test_enrollment_count(self):
        Enrollment.objects.create(student=self.student, course=self.course, is_active=True)
        self.assertEqual(self.course.enrollment_count, 1)

    def test_is_full_false(self):
        self.assertFalse(self.course.is_full)

class CourseViewTest(TestCase):
    def setUp(self):
        self.client = Client()
        self.teacher = User.objects.create_user(username='teacher', email='t@t.com', password='pass', role='teacher')
        self.student = User.objects.create_user(username='student', email='s@s.com', password='pass', role='student')
        self.course = Course.objects.create(
            title='View Test Course', description='desc',
            teacher=self.teacher, status='published', level='beginner', is_free=True
        )

    def test_course_list_view_logged_in(self):
        self.client.login(username='student', password='pass')
        resp = self.client.get(reverse('courses:list'))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'View Test Course')

    def test_course_detail_view(self):
        self.client.login(username='student', password='pass')
        resp = self.client.get(reverse('courses:detail', kwargs={'slug': self.course.slug}))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'View Test Course')

    def test_course_create_requires_login(self):
        resp = self.client.get(reverse('courses:create'))
        self.assertEqual(resp.status_code, 302)

    def test_course_create_as_teacher(self):
        self.client.login(username='teacher', password='pass')
        resp = self.client.get(reverse('courses:create'))
        self.assertEqual(resp.status_code, 200)

    def test_student_cannot_create_course(self):
        self.client.login(username='student', password='pass')
        resp = self.client.get(reverse('courses:create'))
        self.assertEqual(resp.status_code, 403)

    def test_enroll_in_course(self):
        self.client.login(username='student', password='pass')
        self.client.post(reverse('courses:enroll', kwargs={'slug': self.course.slug}))
        self.assertTrue(Enrollment.objects.filter(student=self.student, course=self.course).exists())
